use serde::{Deserialize, Serialize};

/// Filters entered on the topic Data tab. All fields are optional — an
/// all-`None` filter means "pull everything" (per spec: "if filters are
/// empty by default it should pull all messages").
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub struct MessageFilter {
    /// `None` = every partition.
    pub partitions: Option<Vec<i32>>,
    pub max_messages_per_partition: Option<u32>,
    pub max_total_messages: Option<u32>,
    pub from_timestamp_ms: Option<i64>,
    pub to_timestamp_ms: Option<i64>,
    /// An explicit starting offset. When `from_timestamp_ms` is also set,
    /// both apply together (the later/higher of the two resolved start
    /// offsets wins) rather than one overriding the other. Clamped to each
    /// partition's watermark range rather than erroring on a stale/
    /// out-of-range value.
    pub offset: Option<i64>,
    /// The Data tab's "Load message payload" checkbox — when false
    /// (the default), `TopicMessage::payload_base64` comes back `None` for
    /// every row, so a metadata-only browse doesn't pay for encoding/
    /// transferring payload bytes it isn't going to show.
    pub include_payload: bool,
    /// How many payload bytes to actually carry back per message, when
    /// `include_payload` is set. `None` means the whole payload.
    ///
    /// The Data tab's grid renders one line per row and searches only the
    /// first few KB of a value, so shipping whole payloads for it bought
    /// nothing and cost everything: a 1,000-row fetch of 3 MB records moved
    /// ~4 GB of base64 across the IPC boundary (once per streamed message,
    /// then again in the fetch result), and the webview held two copies of it
    /// at once while swapping the streamed rows for the final ones. That is
    /// several times the renderer's memory ceiling, so the app hung and was
    /// killed. Bounded here instead, the same fetch moves a few MB.
    ///
    /// Left `None` by the per-row fetch behind
    /// `MessagePayloadViewer`/`ValueCell`, which needs the real bytes — one
    /// message at a time, which is what makes it affordable.
    pub max_payload_preview_bytes: Option<u32>,
}

/// A single Kafka message header — arbitrary key/value metadata sent
/// alongside a message, separate from its key and payload (e.g.
/// content-type, correlation/trace ids). Unlike a topic/consumer-group name,
/// a header value is an arbitrary byte string in the Kafka protocol — it is
/// NOT guaranteed to be valid UTF-8 (e.g. a binary correlation id), so it's
/// base64-encoded the same way `TopicMessage::payload_base64` is, rather
/// than lossy-UTF-8-decoded (which would silently corrupt binary values).
/// Always populated regardless of the "Load message payload" checkbox,
/// unlike `payload_base64`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MessageHeader {
    pub key: String,
    pub value_base64: Option<String>,
}

/// A batch of incrementally-fetched messages, emitted on the
/// `"messages-batch"` Tauri event as they are polled from the broker, so the
/// Data tab can paint rows as they arrive instead of staying empty until the
/// whole fetch finishes. `request_id` is generated by the frontend and echoed
/// back here so a tab that has since started another fetch (or been stopped)
/// can discard a superseded request's late-arriving events.
///
/// **A batch, not a message.** This carried exactly one message per event
/// until it was measured: a 1,000-message fetch meant 1,000 separate IPC
/// hops, each with its own serialization and its own dispatch into the
/// webview, to paint rows the frontend was already coalescing into ten
/// renders a second at the other end. The batching is done by the command
/// layer's forwarding task (see `connection_fetch_messages`), which is also
/// what decides how long a partial batch may wait.
///
/// Lives here, beside the other types that cross the Rust/TypeScript
/// boundary, rather than in the command layer that emits it: the frontend
/// matches on `requestId`, and a wire type declared away from this module's
/// `rename_all` convention is one nobody checks. When this was declared
/// locally in `commands::connections` it silently serialized `request_id`,
/// every event failed that match, and streaming looked like it simply did
/// not happen.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MessagesBatchEvent {
    pub request_id: String,
    pub messages: Vec<TopicMessage>,
}

/// One row in the Data tab's AG Grid. `payload_base64` is `None` unless the
/// "Load message payload" checkbox was checked for this fetch; when
/// present, it's decoded/rendered client-side (text, JSON, or
/// Avro-with-Confluent-wire-format detection) when the row is clicked, per
/// spec: "message payload should be shown when clicked on the message in
/// right most tab". `key_base64` is base64-encoded rather than decoded to a
/// plain string for the same reason as `MessageHeader::value_base64` — a
/// Kafka message key is an arbitrary byte string, not guaranteed text.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TopicMessage {
    pub partition: i32,
    pub offset: i64,
    pub timestamp_ms: Option<i64>,
    pub key_base64: Option<String>,
    /// The payload, base64-encoded — truncated to the fetch's
    /// [`MessageFilter::max_payload_preview_bytes`] when it set one, so this
    /// is not necessarily the whole message. Compare its decoded length
    /// against `payload_size_bytes` to tell; `None` when the fetch didn't ask
    /// for payloads at all.
    pub payload_base64: Option<String>,
    /// The payload's true length in bytes, whatever `payload_base64` carries
    /// of it. Populated whenever the message has a payload, including on a
    /// metadata-only fetch — a row can then say how big a message is, and the
    /// viewer can tell a truncated preview from a whole small payload, which
    /// a truncated `payload_base64` alone cannot express (a payload cut to
    /// exactly the preview size is indistinguishable from one that happened
    /// to be that long).
    pub payload_size_bytes: Option<u64>,
    pub headers: Vec<MessageHeader>,
}

/// The result of a Data tab fetch: the rows actually pulled (bounded by the
/// filter's max-messages caps), plus how many messages match the same
/// partition/offset/timestamp filter in total, uncapped by those count
/// limits — lets the frontend show "42 loaded of 150 matching" instead of a
/// bare count, so the user can tell whether more remain beyond what was
/// fetched rather than assuming a short result means there's nothing else.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub struct MessageFetchResult {
    pub messages: Vec<TopicMessage>,
    pub total_matching: u64,
    /// The most recent error `consumer.poll()` returned during this fetch,
    /// if any — e.g. a broker-side rejection or a message too large for the
    /// configured `max.partition.fetch.bytes`. Previously these errors were
    /// discarded and treated identically to "no message yet," which made a
    /// stalled fetch on some topics look like a plain empty result with no
    /// way to tell why. `Some` here means the fetch may have returned fewer
    /// messages than `total_matching` promises for a real, diagnosable
    /// reason rather than just running out of time.
    pub poll_error: Option<String>,
    /// Whether the fetch stopped because it had read its payload byte
    /// budget rather than because it satisfied the filter. Every other cap
    /// here counts *messages*, which says nothing about size: on a topic of
    /// multi-megabyte records a 1,000-message fetch is a multi-gigabyte read,
    /// and the count the user typed gives no hint of that. Surfaced so the
    /// Data tab can say the result was cut short and why, instead of silently
    /// showing fewer rows than the filter implies.
    pub stopped_at_byte_budget: bool,
    /// Payload bytes this fetch kept — after any preview truncation, i.e.
    /// what was delivered to the UI rather than what crossed the network.
    /// What the budget above measures, and what the Data tab reports back to
    /// the user.
    pub payload_bytes_read: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regression test for the Data tab never streaming: this event is
    /// matched on the frontend by `requestId`, and it used to be declared in
    /// the command layer without this module's `rename_all`, so it went out
    /// as `request_id`. `event.payload.requestId` was therefore `undefined`
    /// on every single event, the listener's id guard discarded all of them,
    /// and rows only appeared when the finished fetch's result replaced them
    /// wholesale — which read as "streaming does not work".
    #[test]
    fn messages_batch_event_serializes_its_request_id_as_camel_case() {
        let event = MessagesBatchEvent {
            request_id: "req-1".to_string(),
            messages: vec![TopicMessage {
                partition: 0,
                offset: 1,
                timestamp_ms: None,
                key_base64: None,
                payload_base64: None,
                payload_size_bytes: None,
                headers: Vec::new(),
            }],
        };

        let json = serde_json::to_value(&event).unwrap();

        assert!(
            json.get("requestId").is_some(),
            "frontend matches on `requestId`; got keys: {:?}",
            json.as_object().map(|o| o.keys().collect::<Vec<_>>())
        );
        assert!(
            json.get("request_id").is_none(),
            "snake_case key must not be emitted"
        );
        assert_eq!(json["requestId"], "req-1");
    }

    /// The frontend reads `event.payload.messages` and spreads it into its
    /// buffer, so the batch has to arrive as a JSON array under that exact
    /// key — a single `message` object (what this used to send) would leave
    /// the listener spreading `undefined`.
    #[test]
    fn messages_batch_event_carries_its_messages_as_an_array() {
        let message = TopicMessage {
            partition: 3,
            offset: 9,
            timestamp_ms: None,
            key_base64: None,
            payload_base64: None,
            payload_size_bytes: None,
            headers: Vec::new(),
        };
        let event = MessagesBatchEvent {
            request_id: "req-1".to_string(),
            messages: vec![message.clone(), message],
        };

        let json = serde_json::to_value(&event).unwrap();

        assert!(
            json.get("message").is_none(),
            "the single-message key must not be emitted"
        );
        let messages = json["messages"]
            .as_array()
            .expect("`messages` must be an array");
        assert_eq!(messages.len(), 2);
        assert_eq!(messages[0]["partition"], 3);
    }

    #[test]
    fn message_filter_serializes_fields_as_camel_case_and_defaults_to_all_none_and_no_payload() {
        let filter = MessageFilter::default();
        let json = serde_json::to_string(&filter).unwrap();
        assert_eq!(
            json,
            r#"{"partitions":null,"maxMessagesPerPartition":null,"maxTotalMessages":null,"fromTimestampMs":null,"toTimestampMs":null,"offset":null,"includePayload":false,"maxPayloadPreviewBytes":null}"#
        );
    }

    /// The grid only ever renders a few KB of a payload, so the Data tab's
    /// own fetch asks for a bound; the per-row "open this message" fetch
    /// leaves it `None` to get the real bytes.
    #[test]
    fn message_filter_carries_a_payload_preview_bound() {
        let filter = MessageFilter {
            max_payload_preview_bytes: Some(4096),
            ..MessageFilter::default()
        };
        let json = serde_json::to_value(&filter).unwrap();
        assert_eq!(json["maxPayloadPreviewBytes"], 4096);

        let round_tripped: MessageFilter = serde_json::from_value(json).unwrap();
        assert_eq!(round_tripped.max_payload_preview_bytes, Some(4096));
    }

    /// Truncating the payload would otherwise make every message look like it
    /// was exactly the preview size, so the real length travels separately —
    /// it is what tells the UI a payload is partial and must be re-fetched in
    /// full before it can be displayed or decoded.
    #[test]
    fn topic_message_reports_its_true_payload_size_alongside_a_truncated_preview() {
        let message = TopicMessage {
            partition: 0,
            offset: 42,
            timestamp_ms: None,
            key_base64: None,
            payload_base64: Some("eyJpZCI6MX0=".into()),
            payload_size_bytes: Some(3_145_728),
            headers: vec![],
        };
        let json = serde_json::to_value(&message).unwrap();
        assert_eq!(json["payloadSizeBytes"], 3_145_728u64);
    }

    #[test]
    fn topic_message_serializes_fields_as_camel_case_with_payload() {
        let message = TopicMessage {
            partition: 0,
            offset: 42,
            timestamp_ms: Some(1_700_000_000_000),
            key_base64: Some("b3JkZXItMQ==".into()),
            payload_base64: Some("eyJpZCI6MX0=".into()),
            payload_size_bytes: Some(8),
            headers: vec![],
        };
        let json = serde_json::to_string(&message).unwrap();
        assert_eq!(
            json,
            r#"{"partition":0,"offset":42,"timestampMs":1700000000000,"keyBase64":"b3JkZXItMQ==","payloadBase64":"eyJpZCI6MX0=","payloadSizeBytes":8,"headers":[]}"#
        );
    }

    #[test]
    fn topic_message_serializes_a_missing_payload_as_null() {
        let message = TopicMessage {
            partition: 0,
            offset: 42,
            timestamp_ms: None,
            key_base64: None,
            payload_base64: None,
            payload_size_bytes: None,
            headers: vec![],
        };
        let json = serde_json::to_string(&message).unwrap();
        assert!(json.contains(r#""payloadBase64":null"#));
    }

    #[test]
    fn message_header_serializes_fields_as_camel_case() {
        let header = MessageHeader {
            key: "content-type".into(),
            value_base64: Some("YXBwbGljYXRpb24vanNvbg==".into()),
        };
        let json = serde_json::to_string(&header).unwrap();
        assert_eq!(
            json,
            r#"{"key":"content-type","valueBase64":"YXBwbGljYXRpb24vanNvbg=="}"#
        );
    }

    #[test]
    fn message_fetch_result_serializes_fields_as_camel_case() {
        let result = MessageFetchResult {
            messages: vec![TopicMessage {
                partition: 0,
                offset: 1,
                timestamp_ms: None,
                key_base64: None,
                payload_base64: None,
                payload_size_bytes: None,
                headers: vec![],
            }],
            total_matching: 150,
            poll_error: None,
            stopped_at_byte_budget: false,
            payload_bytes_read: 0,
        };
        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains(r#""totalMatching":150"#));
        assert!(json.contains(r#""messages":[{"#));
    }

    /// A count cap can't bound a fetch's size on a topic of multi-megabyte
    /// records — "1000 messages" reads as modest and is several gigabytes.
    /// The byte budget is what actually bounds it, so the result has to say
    /// when it was the budget that ended the fetch rather than the filter.
    #[test]
    fn message_fetch_result_reports_stopping_at_the_byte_budget() {
        let result = MessageFetchResult {
            stopped_at_byte_budget: true,
            payload_bytes_read: 268_435_456,
            ..MessageFetchResult::default()
        };
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(json["stoppedAtByteBudget"], true);
        assert_eq!(json["payloadBytesRead"], 268_435_456u64);
    }

    #[test]
    fn message_fetch_result_defaults_to_not_having_hit_the_byte_budget() {
        let result = MessageFetchResult::default();
        assert!(!result.stopped_at_byte_budget);
        assert_eq!(result.payload_bytes_read, 0);
    }

    #[test]
    fn topic_message_carries_headers() {
        let message = TopicMessage {
            partition: 0,
            offset: 42,
            timestamp_ms: None,
            key_base64: None,
            payload_base64: None,
            headers: vec![
                MessageHeader {
                    key: "trace-id".into(),
                    value_base64: Some("YWJjMTIz".into()),
                },
                MessageHeader {
                    key: "empty".into(),
                    value_base64: None,
                },
            ],
            payload_size_bytes: None,
        };
        let json = serde_json::to_string(&message).unwrap();
        assert!(json.contains(r#""headers":[{"key":"trace-id","valueBase64":"YWJjMTIz"},{"key":"empty","valueBase64":null}]"#));
    }
}
